<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AntDesign" Version="1.6.2" />
    <PackageReference Include="Markdig" Version="0.40.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EzNutrition.Application\EzNutrition.Application.csproj" />
    <ProjectReference Include="..\EzNutrition.Domain\EzNutrition.Domain.csproj" />
    <ProjectReference Include="..\EzNutrition\Shared\EzNutrition.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EzNutrition.Client.Tests" />
  </ItemGroup>

</Project>
