<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e757efb-7a00-4d5d-bf95-30234a20267c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libraries\EzNutrition.AiAgency\EzNutrition.AiAgency.csproj" />
    <ProjectReference Include="..\Hosts\EzNutrition.Client\EzNutrition.Client.csproj" />
    <ProjectReference Include="..\Libraries\EzNutrition.Shared\EzNutrition.Shared.csproj" />
  </ItemGroup>


</Project>
