<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AntDesign" Version="1.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EzNutrition.Archives.Contracts\EzNutrition.Archives.Contracts.csproj" />
    <ProjectReference Include="..\..\EzNutrition.Archives.Xml\EzNutrition.Archives.Xml.csproj" />
    <ProjectReference Include="..\..\EzNutrition.Application\EzNutrition.Application.csproj" />
    <ProjectReference Include="..\..\EzNutrition.Domain\EzNutrition.Domain.csproj" />
    <ProjectReference Include="..\..\EzNutrition.UI\EzNutrition.UI.csproj" />
    <ProjectReference Include="..\Shared\EzNutrition.Shared.csproj" />
  </ItemGroup>

</Project>
