// <auto-generated />
using System;
using EzASD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzASD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231205105109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("EzASD.Data.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("FatherCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatherEduLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatherProfession")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFatherInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGrandmaInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGrandpaInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMotherInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNurseInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnlyChild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainEducationMethods")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotherCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotherEduLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotherProfession")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OthersInFamily")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentsRelationship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryEducator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Respondent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeTogether")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildId");

                    b.ToTable("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
