<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EzNutrition.Archives.Contracts\EzNutrition.Archives.Contracts.csproj" />
    <ProjectReference Include="..\EzNutrition.Domain\EzNutrition.Domain.csproj" />
    <ProjectReference Include="..\EzNutrition.Shared\EzNutrition.Shared.csproj" />
  </ItemGroup>

</Project>
